# Generated by Django 4.2.5 on 2023-09-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='subscription_image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
