# Generated by Django 4.2.5 on 2023-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billbuddy', '0002_alter_bills_subscription_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bills',
            name='subscription_price',
            field=models.CharField(max_length=100),
        ),
    ]
