# Generated by Django 4.2.5 on 2023-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billbuddy', '0003_alter_bills_bill_date_alter_bills_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='subscription_image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
