# Generated by Django 4.2.5 on 2023-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billbuddy', '0004_alter_bills_subscription_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='subscription_image_url',
            field=models.CharField(max_length=400),
        ),
    ]
